version: '3.9'

services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sairahul5583@
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - repms-net
  
  user-service:
    restart: always
    build:
      context: /home/ubuntu/REPMS/backend/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - repms-net
  property-service:
    restart: always
    build:
      context: /home/ubuntu/REPMS/backend/property-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - repms-net

  inquiry-service:
    restart: always
    build:
      context: /home/ubuntu/REPMS/backend/inquiry-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - repms-net

  analytics-service:
    restart: always
    build:
      context: /home/ubuntu/REPMS/backend/analytics-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    networks:
      - repms-net

  profile-service:
    restart: always
    build:
      context: /home/ubuntu/REPMS/backend/profile-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - repms-net

  frontend:
    restart: always
    build:
      context: /home/ubuntu/REPMS/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - repms-net
    depends_on:
      - user-service
      - property-service
      - inquiry-service
      - analytics-service
      - profile-service

volumes:
  pgdata:

networks:
  repms-net:
    driver: bridge